name: Deploy to Commons

on:
  release:
    types:
      - published
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 14
      - run: npm ci
      - run: npm run build --dev
      - env:
          SSH_KEY: ${{ secrets.TOOLFORGE_KEY }}
          SSH_USER: ${{ secrets.TOOLFORGE_USER }}
          USERNAME: ${{ secrets.WIKI_USERNAME }}
          PASSWORD: ${{ secrets.WIKI_PASSWORD }}
        run: |
          mkdir -p ~/.ssh
          echo -e "$SSH_KEY" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          
          eval "$(ssh-agent -s)"
          ssh-add ~/.ssh/id_rsa
          ssh-keyscan -H tools-login.wmflabs.org >> ~/.ssh/known_hosts

          # TODO: move to package.json as a dev tool
          npm install http-proxy-to-socks

          # Create a tunnel in the background, delete the key, and set a TRAP to kill the tunnel on
          # exit.
          ssh -N -D 8080 ${{ secrets.TOOLFORGE_USER }}@tools-login.wmflabs.org &
          SSH_JOB="$!"
          rm ~/.ssh/id_rsa
          
          # This trap will get overrided below, but also set it here just in case HPTS fails to start
          trap "kill $SSH_JOB" EXIT

          ./node_modules/.bin/hpts -s 127.0.0.1:8080 -p 8443 &
          HPTS_JOB="$!"

          # Kill both background jobs on exit
          trap "kill $SSH_JOB ; kill $HPTS_JOB" EXIT
          
          # Run the user's own script to login and publish build results to pages.
          npm run deploy --dev --noi18n
