name: Deploy to Commons

on:
  release:
    types:
      - published
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 14
      # - run: npm ci
      # - run: npm run build --dev
      - env:
          SSH_KEY: ${{ secrets.TOOLFORGE_KEY }}
          SSH_USER: ${{ secrets.TOOLFORGE_USER }}
          USERNAME: ${{ secrets.WIKI_USERNAME }}
          PASSWORD: ${{ secrets.WIKI_PASSWORD }}
        run: |
          mkdir -p ~/.ssh
          echo -e "$SSH_KEY" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          
          eval "$(ssh-agent -s)"
          ssh-add ~/.ssh/id_rsa
          ssh-keyscan -H tools-dev.wmflabs.org >> ~/.ssh/known_hosts

          # Create a tunnel in the background, delete the key, and set a TRAP to kill the tunnel on
          # exit.
          ssh -L 8443 ${{ secrets.TOOLFORGE_USER }}@tools-dev.wmflabs.org &
          rm ~/.ssh/id_rsa

          # Kill the background job on exit
          trap "kill $!" EXIT
          
          curl -L -x socks5h://127.0.0.1:8443 https://ru.wikipedia.org/
          
          # Run the user's own script to login and publish build results to pages.
          # npm run deploy --dev --noi18n
