name: Deploy development build

on:
  push:
    branches:
      - development
    paths:
      - 'src/**'
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 14
      - run: npm ci
      - name: Create a SSH tunnel and deploy
        env:
          SSH_USER: ${{ secrets.TOOLFORGE_USER }}
          SSH_KEY: ${{ secrets.TOOLFORGE_KEY }}
          USERNAME: ${{ secrets.WIKI_USERNAME }}
          PASSWORD: ${{ secrets.WIKI_PASSWORD }}
        run: |
          # Run own script to login and publish the build results to pages.
          npm run deploy --dev --noi18n
