name: Deploy development build

on:
  push:
    branches:
      - development
    paths:
      - 'src/**'
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v1
        with:
          node-version: 14
      - run: npm ci
      - run: npm run build --dev
      - name: Create a SSH tunnel and deploy
        env:
          SSH_USER: ${{ secrets.TOOLFORGE_USER }}
          SSH_KEY: ${{ secrets.TOOLFORGE_KEY }}
          USERNAME: ${{ secrets.WIKI_USERNAME }}
          PASSWORD: ${{ secrets.WIKI_PASSWORD }}
        run: |
          mkdir -p ~/.ssh
          echo -e "$SSH_KEY" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          
          # Create a tunnel in the background.
          ssh -o StrictHostKeyChecking=no -N -D 1081 ${{ secrets.TOOLFORGE_USER }}@tools-login.wmflabs.org &
          SSH_JOB="$!"
          
          # This trap will get overrided below, but also set it here just in case HPTS fails to
          # start.
          trap "kill $SSH_JOB" EXIT
          
          ./node_modules/.bin/hpts -s 127.0.0.1:1081 -p 8080 &
          HPTS_JOB="$!"
          
          # Kill both background jobs on exit.
          trap "kill $SSH_JOB; kill $HPTS_JOB" EXIT
          sleep 3
          rm ~/.ssh/id_rsa
          
          # Run own script to login and publish the build results to pages.
          npm run deploy --dev --noi18n
